# unitconverter.py

import re

def convert_time_to_seconds(time_str):
    """Convert time string (e.g., '5m', '2h') to seconds. (This was generated by AI)"""
    time_regex = re.match(r"(\d+)([smhd])", time_str)
    if not time_regex:
        return None

    value, unit = int(time_regex.group(1)), time_regex.group(2)
    if unit == 's':
        return value
    elif unit == 'm':
        return value * 60
    elif unit == 'h':
        return value * 3600
    elif unit == 'd':
        return value * 86400
    return None
